services:
  postgres:
    image: postgres:alpine
    networks:
      - mooral
    container_name: mooral-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mooral

  redis:
    image: redis:alpine
    networks:
      - mooral
    container_name: mooral-redis
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning

  mailhog:
    image: mailhog/mailhog:latest
    networks:
      - mooral
    container_name: mooral-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MH_STORAGE: memory

  minio:
    image: quay.io/minio/minio:latest
    networks:
      - mooral
    container_name: mooral-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    
  rabbitmq:
    image: rabbitmq:management-alpine
    networks:
      - mooral
    container_name: mooral-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  prometheus:
    image: prom/prometheus:latest
    networks:
      - mooral
    container_name: mooral-prometheus
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    networks:
      - mooral
    container_name: mooral-grafana
    ports:
      - "3000:3000"
      
networks:
  mooral:
    name: mooral-dev-network
    driver: bridge