spring:
  application:
    name: @project.name@
    version: @project.version@
  profiles:
    active: dev
  threads:
    virtual:
      enabled: true
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

server:
  compression:
    enabled: true
    min-response-size: 1024