spring:
  application:
    name: @project.name@
    version: @project.version@
    
  profiles:
    active: dev

  threads:
    virtual:
      enabled: true

  flyway:
    locations: classpath:db/migration

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

  cache:
    type: redis

  rabbitmq:
    listener:
      direct:
        retry:
          enabled: true
          max-attempts: 3

  mail:
    protocol: smtp

server:
  compression:
    enabled: true
    min-response-size: 1024

io:
  github:
    andrehsvictor:
      mooral-api:
        jwt:
          issuer: http://localhost:8080/realms/mooral/protocol/openid-connect
          audience: http://localhost:8080/realms/mooral/protocol/openid-connect
          lifespan:
            - access-token: 15m
            - refresh-token: 7d
            - action-token: 
              - email-verification: 24h
              - password-reset: 1h
              - email-change: 24h