ALTER TABLE board
ADD COLUMN IF NOT EXISTS boards_count INT DEFAULT 0;

ALTER TABLE user
ADD COLUMN IF NOT EXISTS boards_views_count INT DEFAULT 0;

ALTER TABLE user
ADD COLUMN IF NOT EXISTS boards_likes_count INT DEFAULT 0;

ALTER TABLE user
ADD COLUMN IF NOT EXISTS boards_comments_count INT DEFAULT 0;